#! /bin/sh

case "$1" in
	start)

		modprobe scull.ko
		modprobe faulty.ko
		modprobe hello.ko

		;;
	stop)
		echo "Stopping ldd"

		modprobe -r scull
		modprobe -r faulty
		modprobe -r hello

		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
